baseURL = "/"
languageCode = "fr-fr"
title = "Projet Tutoré"
themesDir = "themes"
theme = "hugo-whisper-theme"
enableEmoji = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Analyses"
    url = "/analyses/"
    weight = 2

[params]
    google_analytics_id=""
    homepage_button_link = '/analyses'
    homepage_button_text = 'Analyses'
    homepage_intro = 'Site regroupant nos analyses concernant la transmission du SIDA.'
    # homepage_image = 'https://placekitten.com/1280/800'
    enable_anchor_link = true
    disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]

[params.logo]
    mobile = "/images/logo-mobile.svg"
    standard  = "/images/red_ribbon.svg"

